### ISSUE TITLE
No requirements.txt or clear instructions to actually code

### ISSUE THREAD

**Issue by fredsta98** [DagSonntag/pix2code_improvement#1]
Hi @DagSonntag,

Came back to this project after remembering it from a few years back, ChatGPT got me thinking. Anyway tried to run the original by Tony and I'm having a hard time getting compatible and debugging to run with the the library versions that are now available with python. I found your repo via that repo. However I can't seem to figure which libraries you used to build your improvements. The readme is focused more on the results and methods you used not really how to run your version.

If possible please help me out with error I keep getting with processing the dataset:
![errow](https://user-images.githubusercontent.com/109313193/208902071-3f3ee969-f7b0-4ce7-8e3f-dc1fde571959.png)

I used the exact same data as in the original but I keep getting the errors, I thought maybe there was a missing file in the dataset, however I have checked and the files seem to check out, equal number of both png and gui files.

code:

```
# build_datasets.py
#!/usr/bin/env python
from __future__ import print_function
from __future__ import absolute_import
__author__ = 'Tony Beltramelli - www.tonybeltramelli.com'

import os
import sys
import hashlib
import shutil

from classes.Sampler import *

argv = sys.argv[1:]

if len(argv) < 1:
    print("Error: not enough argument supplied:")
    print("build_datasets.py <input path> <distribution (default: 6)>")
    exit(0)
else:
    input_path = argv[0]

distribution = 6 if len(argv) < 2 else argv[1]

TRAINING_SET_NAME = "training_set"
EVALUATION_SET_NAME = "eval_set"

paths = []
for f in os.listdir(input_path):
    if f.find(".gui") != -1:
        path_gui = "{}/{}".format(input_path, f)
        file_name = f[:f.find(".gui")]

        if os.path.isfile("{}/{}.png".format(input_path, file_name)):
            path_img = "{}/{}.png".format(input_path, file_name)
            paths.append(file_name)

evaluation_samples_number = len(paths) / (distribution + 1)
training_samples_number = evaluation_samples_number * distribution

assert training_samples_number + evaluation_samples_number == len(paths)

print("Splitting datasets, training samples: {}, evaluation samples: {}".format(training_samples_number, evaluation_samples_number))

np.random.shuffle(paths)

eval_set = []
train_set = []

hashes = []
for path in paths:
    if sys.version_info >= (3,):
        f = open("{}/{}.gui".format(input_path, path), 'r', encoding='utf-8')
    else:
        f = open("{}/{}.gui".format(input_path, path), 'r')

    with f:
        chars = ""
        for line in f:
            chars += line
        content_hash = chars.replace(" ", "").replace("\n", "")
        content_hash = hashlib.sha256(content_hash.encode('utf-8')).hexdigest()

        if len(eval_set) == evaluation_samples_number:
            train_set.append(path)
        else:
            is_unique = True
            for h in hashes:
                if h is content_hash:
                    is_unique = False
                    break

            if is_unique:
                eval_set.append(path)
            else:
                train_set.append(path)

        hashes.append(content_hash)

assert len(eval_set) == evaluation_samples_number
assert len(train_set) == training_samples_number

if not os.path.exists("{}/{}".format(os.path.dirname(input_path), EVALUATION_SET_NAME)):
    os.makedirs("{}/{}".format(os.path.dirname(input_path), EVALUATION_SET_NAME))

if not os.path.exists("{}/{}".format(os.path.dirname(input_path), TRAINING_SET_NAME)):
    os.makedirs("{}/{}".format(os.path.dirname(input_path), TRAINING_SET_NAME))

for path in eval_set:
    shutil.copyfile("{}/{}.png".format(input_path, path), "{}/{}/{}.png".format(os.path.dirname(input_path), EVALUATION_SET_NAME, path))
    shutil.copyfile("{}/{}.gui".format(input_path, path), "{}/{}/{}.gui".format(os.path.dirname(input_path), EVALUATION_SET_NAME, path))

for path in train_set:
    shutil.copyfile("{}/{}.png".format(input_path, path), "{}/{}/{}.png".format(os.path.dirname(input_path), TRAINING_SET_NAME, path))
    shutil.copyfile("{}/{}.gui".format(input_path, path), "{}/{}/{}.gui".format(os.path.dirname(input_path), TRAINING_SET_NAME, path))

print("Training dataset: {}/training_set".format(os.path.dirname(input_path), path))
print("Evaluation dataset: {}/eval_set".format(os.path.dirname(input_path), path))

```

**Comment by DagSonntag** [comment]
Hi
Nice that you are taking up this challenge! Should probably be possible to do quite good now with opengpt :) 
Yes, this is does not have an easy requirements or readme, feel free to contribute! I have a notebook that you can use if you want to get going, but otherwise I think the error in you code above is that you treat the 'evaluation_samples_number' as an integer when it does not need to be. 
 So instead of 
`evaluation_samples_number = len(paths) / (distribution + 1)`
use 
`evaluation_samples_number = round(len(paths) / (distribution + 1))` or something to ensure it is an integer. Then do 
`training_samples_number=len(paths)-evaluation_samples_number `

The previous code would have worked before we had an even number of samples (1000 or 1000 or what we had), but not now when some were removed (so we have like 998 or so) (just making up the numbers)

Let me know if it works!

**Comment by fredsta98** [comment]
> Hi Nice that you are taking up this challenge! Should probably be possible to do quite good now with opengpt :) Yes, this is does not have an easy requirements or readme, feel free to contribute! I have a notebook that you can use if you want to get going, but otherwise I think the error in you code above is that you treat the 'evaluation_samples_number' as an integer when it does not need to be. So instead of `evaluation_samples_number = len(paths) / (distribution + 1)` use `evaluation_samples_number = round(len(paths) / (distribution + 1))` or something to ensure it is an integer. Then do `training_samples_number=len(paths)-evaluation_samples_number `
> 
> The previous code would have worked before we had an even number of samples (1000 or 1000 or what we had), but not now when some were removed (so we have like 998 or so) (just making up the numbers)
> 
> Let me know if it works!

Hi @DagSonntag thank you for the quick response, greatly appreciate it!

I apologize in advance for the novel below...

Yes, although the inspiration did come from ChatGPT, I hadn't really gotten a chance to play with it back in 2020, however I was at the time considering building a human augmentation tool for developers based on some of what they were showcasing. unfortunately after using it, and getting to use other extentions and plug-in like TabNine, the results although impressive for a generative model are somewhat disappointing nad I find them unreliable especially for languages like Go or Julia, even some of the python it generates does at first glance look 'good' or 'right' till you run it. It's worth noting though that it not designed to do it for you really...

But its how I arrived back here, back when pix2code was announced I was really excited looking forward to what it could become or at least curious how far it could go before they 'd hit the ceiling. They seem to have made some progress, but don't seem to really have gotten far in comparison to other research out there. I though I may finally take a good look at where the project was coming from and how far we could take it. With programs like midjourney.com allowing UI/UX designers to query it for inspiration, some if not most of the outputs being quite beautiful actually. 
I thought its a shame it only generates images, I was wondering how far pix2code can be improved to being able to take in those images and output bootstrap for example. I realize there are a lot of issues there example:

- Generating the corresponding css for the html it'll generate as opposed to replying just on bootstraps default theme.
- Handling gradients, flex boxes, grids etc...
- I guess most of this could in  a sense be fixed with the DSL, expanding it to frameworks like React would be solved similarly.

Again I'm going for a more human augmentation tool, but with the same idea Tony/Uizard had in mind, to bridge the gap between UI/UX and front-end development. Of course there's a ways to go before pix2code could really get there, but well, gotta start somewhere right?

I added the fixes you suggested and seem to have gotten past that hurdle, thank you so much for the help. I also had to fix a couple issues due to the original source having been built with Tensorflow 1.4 not 2.11.0, which I'm trying to get this to work in, that seemed to have worked up till the training. Where it seem the last few steps in the processing of the dataset may not be behaving as expected. It seems its generating the numpy array from the images but it's not outputting the file : ```meta_dataset.npy``` in the bin folder so when I try to run it I keep getting the following error:



```
2022-12-22 07:51:08.441517: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-22 07:51:09.441656: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2022-12-22 07:51:09.441770: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2022-12-22 07:51:09.441789: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2022-12-22 07:51:12.786706: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:42] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
Loading data...
Generating sparse vectors...
Dataset size: 143674
Vocabulary size: 19
Input shape: (256, 256, 3)
Output size: 19
/content/pix2code/model/classes/dataset/Dataset.py:144: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.save("{}/meta_dataset".format(path), np.array([self.input_shape, self.output_size, self.size]))
Traceback (most recent call last):
  File "./train.py", line 66, in <module>
    run(input_path, output_path, is_memory_intensive=use_generator, pretrained_model=pretrained_weigths)
  File "./train.py", line 20, in run
    dataset.save_metadata(output_path)
  File "/content/pix2code/model/classes/dataset/Dataset.py", line 144, in save_metadata
    np.save("{}/meta_dataset".format(path), np.array([self.input_shape, self.output_size, self.size]))
  File "<__array_function__ internals>", line 5, in save
  File "/usr/local/lib/python3.8/dist-packages/numpy/lib/npyio.py", line 525, in save
    file_ctx = open(file, "wb")
FileNotFoundError: [Errno 2] No such file or directory: '../bin/meta_dataset.npy'
```

**Comment by DagSonntag** [comment]
Hmm, this one I cannot help you with I am afraid. Seems to be some error with your tensorflow enviroment setup.  
The code in this repo worked with tensorflow 2.0, so should be fine with 2.11. The original code do however need some fixups, but should be fairly straightforward if you are used to tensorflow.

**Comment by fredsta98** [comment]
Hi @DagSonntag I managed to fix the issue, the directory it was trying to load the few shot file from was wrong. Thanks for the help. I'm currently training in batches because  I don't have the hardware to load all the data at once. Again thanks for help, I'll let you know how it goes.

**Comment by fredsta98** [comment]
Additionally I'd like to contribute to the project if anyone is still actively working on this...

I managed to train the model with the old source, only up to 10 epochs as default, however when given an input, it seems to always generate the same .gui file, regardless of the input layout, I did take note of the kind of UI it was trained on, I used this image:
![features](https://user-images.githubusercontent.com/109313193/209341356-2663b097-3ae9-4b3c-87af-5b67a5b2a8da.png)

However it gave:
![feature-out](https://user-images.githubusercontent.com/109313193/209341521-e2ef6a41-a01d-48d0-8b20-c8b1e5461fc6.png)

Trying to figure out where I may have been going wrong along the way, and what limitations this might have, and the updates you had made. Additionally, I came across a group that tried to build a discriminator for this: [here](https://towardsdatascience.com/code2pix-deep-learning-compiler-for-graphical-user-interfaces-1256c346950b)

Something I might try as well, after going through your version of the project. I think another thing to note, is the limitations with the DSL dictionary, but that I'll tackle much later I guess. Thank you for you time @DagSonntag I really do appreciate the help on this journey so far.
